"""Init command -- onboard a user from the Navil cloud dashboard to local usage.

Usage:
  navil init              — interactive setup (paste API key, write config)
  navil init --api-key KEY — non-interactive setup
"""

from __future__ import annotations

import argparse
import sys
import uuid
from pathlib import Path
from typing import Any

import httpx
import yaml

# ── Defaults ────────────────────────────────────────────────

DEFAULT_BACKEND_URL = "https://api.navil.ai"
DEFAULT_LISTEN_PORT = 8484
DEFAULT_POLICY_PATH = "./navil-policy.yaml"
CONFIG_DIR = Path.home() / ".navil"
CONFIG_FILE = CONFIG_DIR / "config.yaml"

STARTER_POLICY = """\
# Navil Policy
# Generated by `navil init`
# See https://docs.navil.ai/policies for full reference.

version: "1.0"

rules:
  - name: default-deny-dangerous-tools
    description: Block tools that access the filesystem or run shell commands
    tools_denied:
      - file_system
      - shell
      - exec
    action: deny

  - name: allow-read-only
    description: Allow read-only operations by default
    tools_allowed:
      - "*"
    action_restrictions:
      "*":
        - delete
        - write
"""


# ── API key validation ──────────────────────────────────────


def validate_api_key(api_key: str, backend_url: str = DEFAULT_BACKEND_URL) -> bool:
    """Validate the API key against the cloud backend.

    Sends a GET request to /v1/health with the Authorization header.

    Returns:
        True if the key is valid (HTTP 200), False otherwise.

    Raises:
        httpx.ConnectError: If the backend is unreachable.
    """
    try:
        resp = httpx.get(
            f"{backend_url.rstrip('/')}/v1/health",
            headers={"Authorization": f"Bearer {api_key}"},
            timeout=10.0,
        )
        return resp.status_code == 200
    except (httpx.ConnectError, httpx.TimeoutException, OSError):
        raise


# ── Config generation ───────────────────────────────────────


def build_config(
    api_key: str,
    backend_url: str = DEFAULT_BACKEND_URL,
    listen_port: int = DEFAULT_LISTEN_PORT,
    policy_path: str = DEFAULT_POLICY_PATH,
    sync_enabled: bool = True,
    machine_label: str | None = None,
) -> dict[str, Any]:
    """Build the Navil configuration dictionary."""
    return {
        "cloud": {
            "api_key": api_key,
            "backend_url": backend_url,
            "sync_enabled": sync_enabled,
        },
        "proxy": {
            "listen_port": listen_port,
        },
        "policy": {
            "path": policy_path,
        },
        "machine": {
            "id": str(uuid.uuid4()),
            "label": machine_label,
        },
    }


def write_config(config: dict[str, Any], path: Path = CONFIG_FILE) -> Path:
    """Write config to disk, creating parent directories as needed.

    Returns:
        The path the config was written to.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    header = "# Navil Configuration\n# Generated by `navil init`\n\n"
    path.write_text(header + yaml.dump(config, default_flow_style=False, sort_keys=False))
    return path


def write_starter_policy(policy_path: str = DEFAULT_POLICY_PATH) -> Path:
    """Write a starter policy file.

    Returns:
        The path the policy was written to.
    """
    p = Path(policy_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(STARTER_POLICY)
    return p


# ── Config loading ──────────────────────────────────────────


def load_config(path: Path = CONFIG_FILE) -> dict[str, Any]:
    """Load and return the Navil configuration from disk.

    Returns an empty dict if the config file does not exist or is invalid.
    """
    if not path.exists():
        return {}
    try:
        data = yaml.safe_load(path.read_text())
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def get_machine_id(config: dict[str, Any] | None = None) -> str | None:
    """Return the machine_id from the config, loading from disk if needed."""
    if config is None:
        config = load_config()
    return config.get("machine", {}).get("id")


def ensure_machine_id() -> str:
    """Generate and persist machine_id if not already in config.

    Called on first ``navil wrap`` — no ``navil init`` needed.
    """
    config_path = CONFIG_FILE
    config = load_config(config_path)

    machine_id = config.get("machine", {}).get("id")
    if machine_id:
        return machine_id

    machine_id = str(uuid.uuid4())
    config.setdefault("machine", {})["id"] = machine_id
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(yaml.dump(config, default_flow_style=False))
    return machine_id


def get_machine_label(config: dict[str, Any] | None = None) -> str | None:
    """Return the machine_label from the config, loading from disk if needed."""
    if config is None:
        config = load_config()
    return config.get("machine", {}).get("label")


# ── CLI handler ─────────────────────────────────────────────


def _init_command(cli: Any, args: argparse.Namespace) -> int:
    """Handle `navil init`."""
    config_path = CONFIG_FILE

    # Check for existing config
    if config_path.exists():
        print(f"Configuration already exists at {config_path}")
        answer = input("Overwrite? [y/N] ").strip().lower()
        if answer not in ("y", "yes"):
            print("Aborted.")
            return 1

    # Get API key
    api_key = args.api_key
    if not api_key:
        print("Welcome to Navil!")
        print()
        print("Paste your API key from the Navil dashboard (https://app.navil.ai/settings):")
        try:
            api_key = input("> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nAborted.")
            return 1

    if not api_key:
        print("Error: API key cannot be empty.", file=sys.stderr)
        return 1

    # Validate API key
    print("Validating API key...")
    try:
        valid = validate_api_key(api_key, backend_url=args.backend_url)
    except (httpx.ConnectError, httpx.TimeoutException, OSError):
        print(
            "Cannot reach Navil cloud. Check your connection.",
            file=sys.stderr,
        )
        return 1

    if not valid:
        print(
            "Invalid API key. Please check your key on the Navil dashboard "
            "(https://app.navil.ai/settings).",
            file=sys.stderr,
        )
        return 1

    print("API key validated successfully.")
    print()

    # Write config
    config = build_config(
        api_key=api_key,
        backend_url=args.backend_url,
        listen_port=args.port,
        machine_label=args.machine_label,
    )
    written_path = write_config(config, config_path)
    print(f"Configuration written to {written_path}")

    # Optional starter policy
    if args.with_policy:
        policy_path = write_starter_policy(args.policy_path)
        print(f"Starter policy written to {policy_path}")

    # Next steps
    print()
    print("Setup complete! Next steps:")
    print('  Run `navil proxy start` to begin monitoring')

    return 0


# ── Registration ─────────────────────────────────────────────


def register(subparsers: argparse._SubParsersAction, cli_class: type) -> None:
    """Register the init subcommand."""
    init_parser = subparsers.add_parser(
        "init",
        help="Initialize Navil configuration (onboard from cloud dashboard)",
    )
    init_parser.add_argument(
        "--api-key",
        default=None,
        help="API key from the Navil dashboard (will prompt if not provided)",
    )
    init_parser.add_argument(
        "--backend-url",
        default=DEFAULT_BACKEND_URL,
        help=f"Navil cloud backend URL (default: {DEFAULT_BACKEND_URL})",
    )
    init_parser.add_argument(
        "--port",
        type=int,
        default=DEFAULT_LISTEN_PORT,
        help=f"Proxy listen port (default: {DEFAULT_LISTEN_PORT})",
    )
    init_parser.add_argument(
        "--machine-label",
        default=None,
        help="Optional human-readable label for this machine",
    )
    init_parser.add_argument(
        "--with-policy",
        action="store_true",
        help="Generate a starter policy file",
    )
    init_parser.add_argument(
        "--policy-path",
        default=DEFAULT_POLICY_PATH,
        help=f"Path for the starter policy file (default: {DEFAULT_POLICY_PATH})",
    )
    init_parser.set_defaults(func=lambda cli, args: _init_command(cli, args))
