"""Policy commands -- evaluate security policies for MCP tool calls.

Subcommands:
  check         — evaluate a tool call against the policy
  auto-generate — generate an initial policy from behavioral baselines (zero-config)
  suggest       — show pending policy suggestions from SelfHealingEngine
  rollback      — undo the last N auto-generated policy changes
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

# Default permissive policy for zero-config fallback
_PERMISSIVE_DEFAULT_POLICY: dict[str, Any] = {
    "version": "1.0",
    "agents": {
        "default": {
            "tools_allowed": ["*"],
            "tools_denied": [],
            "actions_allowed": ["read", "write"],
            "rate_limit_per_hour": 1000,
            "data_clearance": "PUBLIC",
        }
    },
    "scopes": {
        "default": {
            "description": "Default scope — all tools visible",
            "tools": "*",
        },
    },
    "suspicious_patterns": [],
}


def _policy_check_command(cli, args: argparse.Namespace) -> int:  # type: ignore[no-untyped-def]
    """Handle policy check command."""
    tool_name = args.tool
    agent_name = args.agent
    action = args.action

    print("\nChecking Policy")
    print(f"Agent: {agent_name}, Tool: {tool_name}, Action: {action}")
    print("-" * 60)

    allowed, reason = cli.policy_engine.check_tool_call(
        agent_name=agent_name, tool_name=tool_name, action=action
    )

    status = "ALLOWED" if allowed else "DENIED"
    print(f"\nPolicy Decision: {status}")
    print(f"Reason: {reason}")

    return 0 if allowed else 1


def _policy_auto_generate_command(cli, args: argparse.Namespace) -> int:  # type: ignore[no-untyped-def]
    """Generate an initial policy from behavioral baselines.

    Zero-config onboarding: if AI generation fails, writes a permissive
    default policy so the first-time experience NEVER fails.
    """
    output_path = Path(args.output)

    print("\n  Navil Policy Auto-Generator")
    print("=" * 60)

    # Try to use AI generation with baselines if available
    generated_policy = None
    try:
        from navil.llm.policy_gen import PolicyGenerator

        gen = PolicyGenerator()

        # Build context from baselines if anomaly detector has data
        baseline_summary = ""
        if hasattr(cli, "anomaly_detector"):
            baselines = getattr(cli.anomaly_detector, "adaptive_baselines", {})
            if baselines:
                parts = []
                for agent_name, ab in baselines.items():
                    parts.append(
                        f"Agent '{agent_name}': "
                        f"tools used: {getattr(ab, 'tool_distribution', {})}, "
                        f"avg rate: {getattr(ab, 'rate_ema', 0):.1f}/min"
                    )
                baseline_summary = "\n".join(parts)

        if baseline_summary:
            description = (
                f"Generate a security policy based on these observed agent behaviors:\n"
                f"{baseline_summary}\n\n"
                f"Apply least-privilege: only allow tools and rates that match observed behavior."
            )
        else:
            description = (
                "Generate a default security policy for an MCP server with:\n"
                "- A default agent profile with reasonable rate limits\n"
                "- Suspicious patterns for common attack vectors\n"
                "- Read-only file system access by default"
            )

        print("  Generating policy with AI...")
        generated_policy = gen.generate(description)

        if generated_policy:
            print("  AI generation successful")
        else:
            print("  AI returned empty policy, using permissive default")

    except Exception as e:
        print(f"  AI generation failed: {e}")
        print("  Using permissive default (zero-config fallback)")

    # Use generated policy or fall back to permissive default
    policy = generated_policy if generated_policy else _PERMISSIVE_DEFAULT_POLICY

    # Write to output
    timestamp = datetime.now(timezone.utc).isoformat()
    header = (
        f"# Auto-generated by navil at {timestamp}\n"
        "# Review and customize for your environment\n\n"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(header)
        yaml.dump(policy, f, default_flow_style=False, sort_keys=False)

    print(f"\n  Policy written to: {output_path}")
    print(f"  Agents defined: {len(policy.get('agents', {}))}")
    print(f"  Scopes defined: {len(policy.get('scopes', {}))}")

    if not generated_policy:
        print("\n  NOTE: This is a permissive default policy.")
        print("  Run 'navil policy suggest' after observing agent behavior")
        print("  to get AI-driven policy recommendations.")

    return 0


def _policy_suggest_command(cli, args: argparse.Namespace) -> int:  # type: ignore[no-untyped-def]
    """Show pending policy suggestions from SelfHealingEngine.

    Like 'git status' for policies — shows what changes are pending.
    Operator approves/rejects each suggestion interactively.
    """
    print("\n  Navil Policy Suggestions")
    print("=" * 60)

    try:
        from navil.llm.self_healing import SelfHealingEngine

        engine = SelfHealingEngine()

        pending = engine.pending_actions
        if not pending:
            print("  No pending suggestions.")
            print("  Run 'navil monitor start' to observe agent behavior,")
            print("  then check back for AI-generated policy suggestions.")
            return 0

        auto_policy_path = Path(args.auto_policy)

        for i, action in enumerate(pending, 1):
            print(f"\n  [{i}/{len(pending)}] {action.get('type', 'unknown')}")
            print(f"    Target:     {action.get('target', 'unknown')}")
            print(f"    Value:      {action.get('value', {})}")
            print(f"    Reason:     {action.get('reason', 'N/A')}")
            print(f"    Confidence: {action.get('confidence', 0):.0%}")
            print(f"    Reversible: {action.get('reversible', False)}")

            if not args.yes:
                response = input("\n    Apply? [y/N/q] ").strip().lower()
                if response == "q":
                    print("  Stopped.")
                    break
                if response != "y":
                    print("    Skipped.")
                    continue

            # Apply the action
            success = engine.apply_action(action, cli.policy_engine, cli.anomaly_detector)
            if success:
                print("    Applied!")
                # Persist to policy.auto.yaml
                if hasattr(cli.policy_engine, "serialize_to_yaml"):
                    cli.policy_engine.auto_policy_file = auto_policy_path
                    cli.policy_engine.serialize_to_yaml()
                    print(f"    Persisted to {auto_policy_path}")
            else:
                print("    Failed to apply.")

        return 0

    except ImportError:
        print("  SelfHealingEngine not available. Install navil[llm] extras.")
        return 1


def _policy_rollback_command(cli, args: argparse.Namespace) -> int:  # type: ignore[no-untyped-def]
    """Undo the last N auto-generated policy changes.

    Reads policy.auto.yaml, strips the last N agent entries that were
    auto-generated, and writes the reduced policy back.
    """
    auto_policy_path = Path(args.auto_policy)
    n = args.count

    print(f"\n  Rolling back last {n} auto-generated policy change(s)")
    print("=" * 60)

    if not auto_policy_path.exists():
        print(f"  No auto-generated policy found at {auto_policy_path}")
        return 1

    try:
        with open(auto_policy_path) as f:
            content = f.read()

        # Parse, skipping the comment header
        policy = yaml.safe_load(content)
        if not isinstance(policy, dict):
            print("  Invalid policy.auto.yaml format")
            return 1

        agents = policy.get("agents", {})
        if not agents:
            print("  No agent rules to roll back")
            return 0

        # Remove the last N agent entries (most recently added)
        agent_names = list(agents.keys())
        to_remove = agent_names[-n:] if n <= len(agent_names) else agent_names

        for name in to_remove:
            del agents[name]
            print(f"    Removed: {name}")

        # Write back
        timestamp = datetime.now(timezone.utc).isoformat()
        header = (
            f"# auto-generated by navil at {timestamp}\n"
            f"# Rolled back {len(to_remove)} entries\n\n"
        )
        with open(auto_policy_path, "w") as f:
            f.write(header)
            yaml.dump(policy, f, default_flow_style=False, sort_keys=False)

        print(f"\n  Rolled back {len(to_remove)} entries from {auto_policy_path}")
        return 0

    except Exception as e:
        print(f"  Rollback failed: {e}")
        return 1


def register(subparsers: argparse._SubParsersAction, cli_class: type) -> None:
    """Register the policy subcommands."""
    policy_parser = subparsers.add_parser("policy", help="Evaluate and manage security policies")
    policy_subparsers = policy_parser.add_subparsers(dest="policy_command")

    # navil policy check
    check_parser = policy_subparsers.add_parser("check", help="Check policy decision")
    check_parser.add_argument("--tool", required=True, help="Tool name")
    check_parser.add_argument("--agent", required=True, help="Agent name")
    check_parser.add_argument("--action", required=True, help="Action (read/write/delete)")
    check_parser.set_defaults(func=lambda cli, args: _policy_check_command(cli, args))

    # navil policy auto-generate
    autogen_parser = policy_subparsers.add_parser(
        "auto-generate",
        help="Generate an initial policy from behavioral baselines (zero-config)",
    )
    autogen_parser.add_argument(
        "--output", default="policy.yaml", help="Output file path (default: policy.yaml)"
    )
    autogen_parser.set_defaults(func=lambda cli, args: _policy_auto_generate_command(cli, args))

    # navil policy suggest
    suggest_parser = policy_subparsers.add_parser(
        "suggest",
        help="Show pending policy suggestions (like 'git status' for policies)",
    )
    suggest_parser.add_argument(
        "--auto-policy",
        default="policy.auto.yaml",
        help="Path to machine-owned policy file (default: policy.auto.yaml)",
    )
    suggest_parser.add_argument(
        "--yes", "-y", action="store_true", help="Auto-approve all suggestions"
    )
    suggest_parser.set_defaults(func=lambda cli, args: _policy_suggest_command(cli, args))

    # navil policy rollback
    rollback_parser = policy_subparsers.add_parser(
        "rollback",
        help="Undo the last N auto-generated policy changes",
    )
    rollback_parser.add_argument(
        "--auto-policy",
        default="policy.auto.yaml",
        help="Path to machine-owned policy file (default: policy.auto.yaml)",
    )
    rollback_parser.add_argument(
        "--count", "-n", type=int, default=1, help="Number of changes to undo (default: 1)"
    )
    rollback_parser.set_defaults(func=lambda cli, args: _policy_rollback_command(cli, args))
