"""OpenAPI MCP Server — lightweight stdio MCP server that proxies to a REST API.

Loads a Navil bridge config (generated by ``openapi_bridge``), exposes each
OpenAPI endpoint as an MCP tool, and translates MCP ``tools/call`` requests
into HTTP calls against the real API server.

This server is designed to be spawned by ``navil shim`` so that every tool
call goes through Navil's full security stack (policy, anomaly detection,
telemetry) before reaching the API.

Usage:
    python -m navil.openapi_server /path/to/.navil-openapi-petstore.json

Architecture:
    MCP Client  <-->  navil shim  <-->  openapi_server  --> HTTP --> REST API
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import sys
from pathlib import Path
from typing import Any

import httpx

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# JSON-RPC helpers
# ---------------------------------------------------------------------------


def _jsonrpc_response(result: Any, req_id: Any) -> dict[str, Any]:
    return {"jsonrpc": "2.0", "result": result, "id": req_id}


def _jsonrpc_error(code: int, message: str, req_id: Any) -> dict[str, Any]:
    return {"jsonrpc": "2.0", "error": {"code": code, "message": message}, "id": req_id}


def _write_message(data: bytes) -> None:
    """Write a JSON-RPC message with Content-Length framing to stdout."""
    header = f"Content-Length: {len(data)}\r\n\r\n".encode()
    sys.stdout.buffer.write(header + data)
    sys.stdout.buffer.flush()


async def _read_message(reader: asyncio.StreamReader) -> bytes | None:
    """Read one JSON-RPC message (Content-Length or NDJSON framing)."""
    try:
        line = await reader.readline()
    except (asyncio.IncompleteReadError, ConnectionResetError):
        return None
    if not line:
        return None

    stripped = line.strip()

    # Content-Length framing
    if stripped.lower().startswith(b"content-length:"):
        length_str = stripped.split(b":", 1)[1].strip()
        try:
            content_length = int(length_str)
        except ValueError:
            return None
        # Read until blank line
        while True:
            header_line = await reader.readline()
            if not header_line or header_line.strip() == b"":
                break
        try:
            body = await reader.readexactly(content_length)
        except (asyncio.IncompleteReadError, ConnectionResetError):
            return None
        return body

    # NDJSON framing
    if stripped:
        return stripped

    return await _read_message(reader)


# ---------------------------------------------------------------------------
# HTTP translation
# ---------------------------------------------------------------------------


def _build_url(base_url: str, path_template: str, params: dict[str, Any]) -> str:
    """Build the target URL, substituting path parameters."""
    url = base_url.rstrip("/") + path_template
    # Replace {param} placeholders
    for name, value in list(params.items()):
        placeholder = "{" + name + "}"
        if placeholder in url:
            url = url.replace(placeholder, str(value))
    return url


def _split_params(
    tool_def: dict[str, Any], arguments: dict[str, Any]
) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    """Split arguments into path, query, and body params based on x-param-location."""
    path_params: dict[str, Any] = {}
    query_params: dict[str, Any] = {}
    body_params: dict[str, Any] = {}

    schema = tool_def.get("inputSchema", {})
    properties = schema.get("properties", {})

    for name, value in arguments.items():
        prop = properties.get(name, {})
        location = prop.get("x-param-location", "query")

        if location == "path":
            path_params[name] = value
        elif location == "body":
            body_params[name] = value
        elif location == "header":
            # Headers handled separately in future; treat as query for now
            query_params[name] = value
        else:
            query_params[name] = value

    return path_params, query_params, body_params


async def _execute_http_request(
    client: httpx.AsyncClient,
    tool_def: dict[str, Any],
    arguments: dict[str, Any],
    base_url: str,
) -> dict[str, Any]:
    """Translate an MCP tool call into an HTTP request and return the result."""
    method = tool_def["method"]
    path = tool_def["path"]

    path_params, query_params, body_params = _split_params(tool_def, arguments)
    url = _build_url(base_url, path, path_params)

    kwargs: dict[str, Any] = {"params": query_params if query_params else None}

    if method in ("POST", "PUT", "PATCH") and body_params:
        kwargs["json"] = body_params
    elif method in ("POST", "PUT", "PATCH") and "body" in arguments:
        # Single "body" param wrapping
        kwargs["json"] = arguments["body"]

    try:
        response = await client.request(method, url, **kwargs)
        # Build result
        content_type = response.headers.get("content-type", "")
        if "json" in content_type:
            try:
                body = response.json()
            except Exception:
                body = response.text
        else:
            body = response.text

        return {
            "content": [
                {
                    "type": "text",
                    "text": json.dumps(body) if not isinstance(body, str) else body,
                }
            ],
            "status_code": response.status_code,
        }
    except httpx.RequestError as exc:
        return {
            "content": [{"type": "text", "text": f"HTTP request failed: {exc}"}],
            "isError": True,
        }


# ---------------------------------------------------------------------------
# MCP Server
# ---------------------------------------------------------------------------


class OpenAPIMCPServer:
    """Stdio MCP server that exposes OpenAPI endpoints as MCP tools."""

    def __init__(self, config: dict[str, Any]) -> None:
        self.base_url = config["base_url"]
        self.tools = config["tools"]
        self._tools_by_name: dict[str, dict[str, Any]] = {t["name"]: t for t in self.tools}
        self._client: httpx.AsyncClient | None = None

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None:
            self._client = httpx.AsyncClient(timeout=30.0)
        return self._client

    def _handle_initialize(self, params: dict[str, Any], req_id: Any) -> dict[str, Any]:
        """Handle the ``initialize`` MCP request."""
        return _jsonrpc_response(
            {
                "protocolVersion": "2024-11-05",
                "capabilities": {"tools": {"listChanged": False}},
                "serverInfo": {
                    "name": "navil-openapi-bridge",
                    "version": "0.2.0",
                },
            },
            req_id,
        )

    def _handle_tools_list(self, req_id: Any) -> dict[str, Any]:
        """Handle ``tools/list`` — return all available tools."""
        tool_defs = []
        for tool in self.tools:
            # Build clean tool descriptor (no internal fields)
            clean_schema = dict(tool["inputSchema"])
            # Remove x-param-location from properties for client consumption
            if "properties" in clean_schema:
                cleaned_props = {}
                for name, prop in clean_schema["properties"].items():
                    prop_copy = {k: v for k, v in prop.items() if not k.startswith("x-")}
                    cleaned_props[name] = prop_copy
                clean_schema["properties"] = cleaned_props

            tool_defs.append(
                {
                    "name": tool["name"],
                    "description": tool.get("description", ""),
                    "inputSchema": clean_schema,
                }
            )

        return _jsonrpc_response({"tools": tool_defs}, req_id)

    async def _handle_tools_call(
        self, params: dict[str, Any], req_id: Any
    ) -> dict[str, Any]:
        """Handle ``tools/call`` — execute the HTTP request."""
        tool_name = params.get("name", "")
        arguments = params.get("arguments", {})

        tool_def = self._tools_by_name.get(tool_name)
        if not tool_def:
            return _jsonrpc_error(-32602, f"Unknown tool: {tool_name}", req_id)

        client = await self._get_client()
        result = await _execute_http_request(client, tool_def, arguments, self.base_url)
        return _jsonrpc_response(result, req_id)

    async def handle_message(self, raw: bytes) -> bytes | None:
        """Process a single JSON-RPC message and return the response bytes."""
        try:
            msg = json.loads(raw)
        except json.JSONDecodeError:
            resp = _jsonrpc_error(-32700, "Parse error", None)
            return json.dumps(resp).encode()

        method = msg.get("method", "")
        req_id = msg.get("id")
        params = msg.get("params", {})

        # Notifications (no id) — acknowledge but no response
        if req_id is None and method == "notifications/initialized":
            return None

        if method == "initialize":
            resp = self._handle_initialize(params, req_id)
        elif method == "tools/list":
            resp = self._handle_tools_list(req_id)
        elif method == "tools/call":
            resp = await self._handle_tools_call(params, req_id)
        elif method == "ping":
            resp = _jsonrpc_response({}, req_id)
        else:
            resp = _jsonrpc_error(-32601, f"Method not found: {method}", req_id)

        return json.dumps(resp).encode()

    async def run(self) -> int:
        """Main event loop: read from stdin, process, write to stdout."""
        reader = asyncio.StreamReader()
        protocol = asyncio.StreamReaderProtocol(reader)
        loop = asyncio.get_event_loop()
        await loop.connect_read_pipe(lambda: protocol, sys.stdin.buffer)

        while True:
            raw = await _read_message(reader)
            if raw is None:
                break  # EOF

            response_bytes = await self.handle_message(raw)
            if response_bytes is not None:
                _write_message(response_bytes)

        if self._client:
            await self._client.aclose()

        return 0


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    """CLI entry point for ``python -m navil.openapi_server``."""
    if len(sys.argv) < 2:
        print("Usage: python -m navil.openapi_server <bridge-config.json>", file=sys.stderr)
        return 1

    config_path = sys.argv[1]
    path = Path(config_path)
    if not path.exists():
        print(f"Error: config not found: {config_path}", file=sys.stderr)
        return 1

    config = json.loads(path.read_text())

    logging.basicConfig(
        stream=sys.stderr,
        level=logging.WARNING,
        format="%(asctime)s [navil-openapi] %(levelname)s %(message)s",
        force=True,
    )

    server = OpenAPIMCPServer(config)
    return asyncio.run(server.run())


if __name__ == "__main__":
    sys.exit(main())
